version: '3'

services:
  db:
    # build:  .   <-- instead image:
      # dockerfile: Dockerfile-for-scripts-alternate
    image: mysql:latest
    container_name: db
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=test
    - MYSQL_PASSWORD=root
    volumes:
    - "./.data/db:/var/lib/mysql"
  webapp:
    image: ustrd/webapp:2.0
    container_name: webapp
    depends_on:
    - db
    ports:
    - 8080:8080
    environment:
    - DATABASE_HOST=db
    - DATABASE_USER=root
    - DATABASE_PASSWORD=root
    - DATABASE_NAME=butterfly
    - DATABASE_PORT=3306
    # Compose does not support 'deploy' configuration - use `docker stack deploy` to deploy
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 1000M
      restart_policy:
        condition: on-failure

